# Generated by Django 2.2.22 on 2021-06-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='ReserveRoom',
        ),
    ]
