# Generated by Django 2.2.22 on 2021-06-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210616_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveroom',
            name='date',
            field=models.DateField(),
        ),
    ]
