# Generated by Django 2.2.22 on 2021-06-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210616_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReserveRoom',
            new_name='Reservation',
        ),
    ]
